### ISSUE TITLE
paper can't find.

### ISSUE THREAD

**Issue by jay2012-lin** [Shen-Lab/SS-GCNs#1]
Thank you for your excellent work. May I have a look at your paper? I can't find the original paper on the Internet.

**Comment by yyou1996** [comment]
Hi @linqika95,

Thank you for your interest. The paper is under revision now and will be released asap (I will also notify you in this issue).

**Comment by yyou1996** [comment]
Hi @linqika95,

We just release our arXiv version:
https://arxiv.org/abs/2006.09136

Thank you again for your interest.
