### ISSUE TITLE
what is the mean of cluster_labels?

### ISSUE THREAD

**Issue by cquzys** [Shen-Lab/SS-GCNs#2]
Hello:
  Thanks for your good jobs, but I do not know how can we obtain the datasets in folder clustrer_labels? what is the difference between ss_lables and labels?

thank you!

**Comment by yyou1996** [comment]
Hi @cquzys,

Thanks for your interest in our work. In the code, I pre-calculate ss_labels for node clustering ss task to accelerate the experiments, and therefore for ss_labels in node clustering task I just load the clustrer_labels, while other tasks the ss_labels are generated during code running. Thank you for the reminder of it and I will upload the clustrer_labels generation code to avoid further confusion (simply k-means cluster based on node features).

**Comment by yyou1996** [comment]
cluster_labels generation code is uploaded:
https://github.com/Shen-Lab/SS-GCNs/blob/master/SS-GCNs/clu.py
